/**
 * SessionMonitor — Background error/crash reporter for production builds.
 *
 * Captures uncaught errors, unhandled promise rejections, and console.error calls.
 * Batches them and auto-submits to GitHub Issues via the submit_bug_report Tauri command.
 *
 * Runs silently in the background — no UI. Mount once in App.jsx.
 */
import { useEffect, useRef } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { APP_VERSION } from '../version';

// ── Config ──
const BATCH_INTERVAL_MS = 5 * 60 * 1000; // Flush every 5 minutes
const MAX_QUEUE = 50;                      // Max errors before force-flush
const DEDUP_WINDOW_MS = 30_000;            // Suppress identical errors within 30s
const SESSION_KEY = 'codex_monitor_session_id';
const LAST_REPORT_KEY = 'codex_monitor_last_report';

// ── Module-level state (survives re-renders) ──
const errorQueue = [];
const fingerprints = new Map();
let sessionId = null;
let sessionStart = null;
let flushing = false;

function getSessionId() {
  if (sessionId) return sessionId;
  sessionId = Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 6);
  sessionStart = new Date().toISOString();
  try { sessionStorage.setItem(SESSION_KEY, sessionId); } catch {}
  return sessionId;
}

function normalizeForFingerprint(msg) {
  if (!msg) return '';
  return msg
    .replace(/\d{4}-\d{2}-\d{2}T[\d:.]+Z?/g, '')
    .replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi, '')
    .replace(/\b\d{5,}\b/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function shouldCapture(msg) {
  if (!msg) return false;
  // Skip React dev warnings — not real bugs
  const skip = [
    /Each child in a list should have a unique "key"/,
    /Warning: React does not recognize/,
    /Warning: validateDOMNesting/,
    /Warning: Unknown prop/,
    /Download the React DevTools/,
    /Warning: Can't perform a React state update on an unmounted/,
    /Warning: Cannot update a component/,
    /ResizeObserver loop/,
    /Failed to fetch dynamically imported module/,
  ];
  return !skip.some(p => p.test(msg));
}

function enqueueError(entry) {
  const fp = normalizeForFingerprint(entry.message);
  const now = Date.now();
  const prev = fingerprints.get(fp);
  if (prev && now - prev < DEDUP_WINDOW_MS) return;
  fingerprints.set(fp, now);

  errorQueue.push({
    ...entry,
    timestamp: new Date().toISOString(),
    session: getSessionId(),
    version: APP_VERSION,
    url: window.location.hash || window.location.pathname,
  });

  // Force flush if queue is large
  if (errorQueue.length >= MAX_QUEUE) {
    flushErrors();
  }
}

async function flushErrors() {
  if (flushing || errorQueue.length === 0) return;
  flushing = true;

  const batch = errorQueue.splice(0, MAX_QUEUE);

  // Rate limit: max 1 report per 10 minutes
  try {
    const lastReport = localStorage.getItem(LAST_REPORT_KEY);
    if (lastReport && Date.now() - parseInt(lastReport, 10) < 10 * 60 * 1000) {
      // Too soon — put errors back and wait
      errorQueue.unshift(...batch);
      flushing = false;
      return;
    }
  } catch {}

  // Group by type
  const errorsByType = {};
  for (const e of batch) {
    const key = normalizeForFingerprint(e.message);
    if (!errorsByType[key]) {
      errorsByType[key] = { ...e, count: 1 };
    } else {
      errorsByType[key].count++;
    }
  }

  const uniqueErrors = Object.values(errorsByType);
  const title = `[Auto] Session Monitor: ${uniqueErrors.length} error${uniqueErrors.length !== 1 ? 's' : ''} in ${APP_VERSION}`;

  const errorLines = uniqueErrors.map((e, i) => {
    let line = `### ${i + 1}. ${e.type} ${e.count > 1 ? `(x${e.count})` : ''}\n`;
    line += `**Message:** \`${(e.message || '').slice(0, 300)}\`\n`;
    if (e.filename) line += `**File:** \`${e.filename}\`${e.lineno ? `:${e.lineno}` : ''}\n`;
    if (e.stack) line += `<details><summary>Stack trace</summary>\n\n\`\`\`\n${e.stack.slice(0, 800)}\n\`\`\`\n</details>\n`;
    line += `**Page:** \`${e.url}\` | **Time:** ${e.timestamp}\n`;
    return line;
  }).join('\n---\n\n');

  const body = `## Automated Session Monitor Report

**App Version:** ${APP_VERSION}
**Session:** \`${getSessionId()}\`
**Session Start:** ${sessionStart}
**Report Time:** ${new Date().toISOString()}
**OS:** ${navigator.platform}
**Screen:** ${screen.width}x${screen.height} @ ${window.devicePixelRatio}x
**Errors in batch:** ${batch.length} (${uniqueErrors.length} unique)

---

${errorLines}

---
*Auto-generated by The Codex Session Monitor*`;

  try {
    await invoke('submit_bug_report', { title, body });
    try { localStorage.setItem(LAST_REPORT_KEY, Date.now().toString()); } catch {}
  } catch {
    // If submit fails, errors are lost — that's fine for auto-reports
  }

  flushing = false;
}

export default function SessionMonitor() {
  const intervalRef = useRef(null);
  const origConsoleError = useRef(null);

  useEffect(() => {
    getSessionId();

    // ── 1. Capture window errors ──
    const handleError = (event) => {
      const msg = event.message || 'Unknown error';
      if (!shouldCapture(msg)) return;
      enqueueError({
        type: 'uncaught_error',
        message: msg,
        filename: event.filename || '',
        lineno: event.lineno || 0,
        colno: event.colno || 0,
        stack: event.error?.stack || '',
      });
    };

    // ── 2. Capture unhandled promise rejections ──
    const handleRejection = (event) => {
      const reason = event.reason;
      const msg = reason?.message || String(reason) || 'Unhandled promise rejection';
      if (!shouldCapture(msg)) return;
      enqueueError({
        type: 'unhandled_rejection',
        message: msg,
        stack: reason?.stack || '',
      });
    };

    // ── 3. Intercept console.error for serious errors ──
    if (!origConsoleError.current) {
      origConsoleError.current = console.error;
    }
    const origErr = origConsoleError.current;
    console.error = (...args) => {
      origErr.apply(console, args);
      const msg = args.map(a => {
        if (a instanceof Error) return a.message;
        if (typeof a === 'string') return a;
        try { return JSON.stringify(a); } catch { return String(a); }
      }).join(' ');

      if (!shouldCapture(msg)) return;
      // Only capture actual errors, not warnings piped through console.error
      if (msg.startsWith('Warning:')) return;

      const errorObj = args.find(a => a instanceof Error);
      enqueueError({
        type: 'console_error',
        message: msg.slice(0, 500),
        stack: errorObj?.stack || '',
      });
    };

    window.addEventListener('error', handleError);
    window.addEventListener('unhandledrejection', handleRejection);

    // ── 4. Periodic flush ──
    intervalRef.current = setInterval(flushErrors, BATCH_INTERVAL_MS);

    // ── 5. Flush on page unload ──
    const handleUnload = () => { flushErrors(); };
    window.addEventListener('beforeunload', handleUnload);

    return () => {
      window.removeEventListener('error', handleError);
      window.removeEventListener('unhandledrejection', handleRejection);
      window.removeEventListener('beforeunload', handleUnload);
      if (intervalRef.current) clearInterval(intervalRef.current);
      if (origConsoleError.current) {
        console.error = origConsoleError.current;
      }
      // Final flush
      flushErrors();
    };
  }, []);

  return null; // No UI — pure background monitor
}
